### PR TITLE
cross compile to 2.12.0

### PR DESCRIPTION
**Pull request by MasseGuillaume**
`+modules/test` and +modules/publishLocal` works fine

there are two failing test in HorizontalTests

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
the ci fails because you need to publishLocal derive & other libs

**Comment by lespea** [comment]
This should probably be updated to 2.12 proper.

**Comment by MasseGuillaume** [comment]
@lespea 2.12.0 is not released yet. I know it's on maven central, but it was not announced.

**Comment by lespea** [comment]
Good point

**Comment by lihaoyi** [comment]
SHouldn't be hard to get this out for 2.12.0-final, but uPickle uses a bunch of random stuff in it's test suite to make sure the derivation doesn't blow up so we'll need to wait till all that stuff is published

**Comment by MasseGuillaume** [comment]
@lihaoyi I just disable it: 
https://github.com/lihaoyi/upickle-pprint/pull/179/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR220

**Comment by lihaoyi** [comment]
Only missing dependency i bumped into for 2.12-final is @non's 

[ ] `org.spire-math:jawn-parser_2.12:0.10.2`

**Comment by lihaoyi** [comment]
This makes this pass on 2.12.0

```diff
LIs-MacBook-Pro:upickle-pprint lihaoyi$ git diff
diff --git a/build.sbt b/build.sbt
index 273c6ab..1e784e4 100644
--- a/build.sbt
+++ b/build.sbt
@@ -4,7 +4,7 @@ val settings = Seq(
   version := upicklePPrint.Constants.version,

   scalaVersion := "2.11.8",
-  crossScalaVersions := Seq("2.10.6", "2.11.8", "2.12.0-RC2"),
+  crossScalaVersions := Seq("2.10.6", "2.11.8", "2.12.0"),

   scalacOptions := Seq("-unchecked",
     "-deprecation",
@@ -30,7 +30,7 @@ val settings = Seq(
   libraryDependencies ++= Seq(
     "com.lihaoyi" %% "acyclic" % "0.1.5" % "provided",
     "com.lihaoyi" %%% "utest" % "0.4.4" % "test",
-    "com.lihaoyi" %%% "sourcecode" % "0.2.0",
+    "com.lihaoyi" %%% "sourcecode" % "0.1.3",
     "org.scala-lang" % "scala-reflect" % scalaVersion.value % "provided",
     "org.scala-lang" % "scala-compiler" % scalaVersion.value % "provided"
   ) ++ (
@@ -51,7 +51,7 @@ settings

 val compatible211and212 =
   unmanagedSourceDirectories in Compile ++= {
-    if (Set("2.11", "2.12.0-RC2").contains(scalaBinaryVersion.value))
+    if (Set("2.11", "2.12").contains(scalaBinaryVersion.value))
       Seq(baseDirectory.value / ".." / "shared" / "src" / "main" / "scala-2.11_2.12")
     else
       Seq()
```

**Comment by lorandszakacs** [comment]
Just chiming in to mention that scala `2.12.0` final has been released :smile:. Keep up the good work!

**Comment by MasseGuillaume** [comment]
@lihaoyi should be ready now. I ran the test locally, it works fine ;-). Travis is a bit stuck on memory.

**Comment by stuhood** [comment]
Thanks for doing this!

Any idea when the first publish for 2.12.0 will go out?

**Comment by lihaoyi** [comment]
@stuhood It's out already under 0.4.4

**Pull request merged**
