### PR TITLE
be 2.13 friendly

### PR DESCRIPTION
**Pull request by SethTisue**
for the Scala 2.13 community build (yup, there already is one)

### CODE REVIEW

**Comment by SethTisue** [comment]
I also threw 2.12.0 into .travis.yml on the assumption its absence there was inadvertent

**Comment by SethTisue** [comment]
the 2.12.0 build failed with "java.lang.UnsupportedClassVersionError: scala/tools/nsc/Main : Unsupported major.minor version 52.0" so I guess there's more work to be done there. it's not really related to the main change I want here, so I have pushed a revised commit that leaves that part out

**Comment by SethTisue** [comment]
the remaining Travis failures are unrelated to my changes, I believe — they are seen elsewhere at e.g. https://travis-ci.org/lihaoyi/upickle-pprint/jobs/173883852. could this be merged regardless?

**Comment by SethTisue** [comment]
@lihaoyi can this be merged?

**Comment by lihaoyi** [comment]
Sorry I've been busy with work and haven't had a chance to un-bork my build...

**Comment by SethTisue** [comment]
@japgolly is this a repo where you now have mighty powers?

**Comment by japgolly** [comment]
@SethTisue Nay. I'm but one of the small folk in this land.

**Comment by SethTisue** [comment]
upickle is being put to sleep, so we can just drop this

**Pull request closed without merging**
