### PR TITLE
Reading unquoted numbers as longs

### PR DESCRIPTION
**Pull request by senia-psm**
https://github.com/lihaoyi/upickle/issues/66

### CODE REVIEW

**Comment by lihaoyi** [comment]
I'm gonna not-merge this since it's trivial to set this up in your own project. It introduces an asymmetry between reading and writing I'm not comfortable with including in mainline by default

**Comment by lihaoyi** [comment]
Just C&P that exact snippet into your own object and import it where you want this behavior =)

**Comment by senia-psm** [comment]
@lihaoyi, you already have this kind of asymmetry in all `NumericReadWriter`: read `Str` and `Num`, write `Num`.

**Comment by lihaoyi** [comment]
AFAICT that writes `Num`s and `Str`s too because `Infinity` and `-Infinity` cannot be represented as JSON numbers

**Pull request closed without merging**
